language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate --quiet

install:
  - composer install

before_script:
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - composer pkg_test

notifications:
  email:
    recipients:
      - developer@bigmichi1.de
    on_success: always
    on_failure: always
    on_start: false
